[package]
name = "comdex-bindings"
version = "0.6.0"
authors = ["Comdex"]
edition = "2018"
description = "Bindings for CustomMsg and CustomQuery for the Comdex blockchain"


[dependencies]
cosmwasm-std = "1.0.0-beta8"
schemars = "0.8"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

[dev-dependencies]
cosmwasm-schema = "1.0.0-beta8"
